# Generated by Django 5.2.7 on 2025-10-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='edited_at',
            new_name='edit_date',
        ),
    ]
