# Generated by Django 5.2.7 on 2025-10-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_created_at_message_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='announcement_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
