# Generated by Django 5.2.7 on 2025-10-26 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_announcement_and_cleanup_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('A1', 'Room A1'), ('A2', 'Room A2'), ('A3', 'Room A3'), ('B1', 'Room B1'), ('B2', 'Room B2'), ('B3', 'Room B3'), ('Lab1', 'Computer Lab 1'), ('Lab2', 'Computer Lab 2')], max_length=50)),
                ('subject', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('English', 'English'), ('History', 'History')], max_length=100)),
                ('course', models.CharField(choices=[('GCSE', 'GCSE'), ('A-Level', 'A-Level'), ('Year 7', 'Year 7'), ('Year 8', 'Year 8'), ('Year 9', 'Year 9'), ('Year 10', 'Year 10'), ('Year 11', 'Year 11'), ('Year 12', 'Year 12'), ('Year 13', 'Year 13')], max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Schedule Entries',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
