# Generated by Django 5.2.7 on 2025-10-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheduleentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='notes',
        ),
    ]
