# Generated by Django 5.2.7 on 2025-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_scheduleentry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='course',
            field=models.CharField(choices=[('GCSE', 'GCSE'), ('IB', 'IB'), ('Year 7', 'Year 7'), ('Year 8', 'Year 8'), ('Year 9', 'Year 9')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='room',
            field=models.CharField(choices=[('CS1', 'CS Lab 1'), ('CS2', 'CS Lab 2'), ('CS3', 'CS Lab 3'), ('FABLAB', 'Fablab')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='subject',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('DT', 'Design Technology')], max_length=100),
        ),
    ]
