# Generated by Django 5.2.7 on 2025-10-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_scheduleentry_room_classroom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
    ]
