# Generated by Django 5.2.7 on 2025-11-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='RoomMembership',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
