# Generated by Django 5.2.7 on 2025-11-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_room_unique_together_remove_room_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='recurrence_group',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='recurrence_index',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='recurrence_interval_days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='recurrence_total_occurrences',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
