# Generated by Django 5.2.7 on 2025-11-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_enforce_scheduleentry_group_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='private_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
